### PR TITLE
Add support to build/run C++ tests on native_posix

### LINKED ISSUE #19: libstdc++ library missing for C++ apps in docker
Some C++ library missing in docker.

https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/20996/1/console

https://github.com/zephyrproject-rtos/zephyr/pull/9533

```
[100%] Linking CXX executable zephyr.elf
/usr/bin/x86_64-linux-gnu-ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.so when searching for -lstdc++
/usr/bin/x86_64-linux-gnu-ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.a when searching for -lstdc++
/usr/bin/x86_64-linux-gnu-ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Add support to build/run C++ tests on native_posix by adding g++ multilib support and bumping gcc/g++ to latest stable version (9)  to add C++17 support.

Fixes: #19

### CODE REVIEW

**Comment by vanwinkeljan** [comment]
@pabigot @finikorg @aescolar fyi

**Review by pabigot — DISMISSED** [review]
Looks fine, not something I can test.

**Comment by vanwinkeljan** [comment]
> not something I can test.

I did some basic tests with the container by running sanitycheck for native_posix & native_posix_64 inside the container and none of the tests failed. (the test run included running the `cpp` and `libcxx`)

**Comment by galak** [comment]
Can we split this PR.  The change to GCC9 has other impacts that need more testing.

**Comment by vanwinkeljan** [comment]
> The change to GCC9 has other impacts that need more testing.

@galak I did run all native_posix(_64) tests against a successfully generated docker container.
So I would assume all impact has been covered or did I miss something?

**Comment by galak** [comment]
> > The change to GCC9 has other impacts that need more testing.
> 
> @galak I did run all native_posix(_64) tests against a successfully generated docker container.
> So I would assume all impact has been covered or did I miss something?

The container is used for building the SDK for example, so need to see if there's an impact there.

**Review by galak — APPROVED** [review]

**Pull request merged**
