### PR TITLE
Consolidate into one Docker file and remove shippable old files

### PR DESCRIPTION
**Pull request by nashif**
End goal is to make https://github.com/zephyrproject-rtos/docker-image build on top of this one, eventually move all into one repo and maintain changes in one place only.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Can we do the move to ubuntu-20.04 as a separate PR?

I think we should make one last release of the 18.04 with all the other changes and than have ubuntu-20.04 change version to v1.0.0

**Comment by nashif** [comment]
> Can we do the move to ubuntu-20.04 as a separate PR?

what is the value of this? This is just unnecessary work IMO. I would rather spend the time on verifying this all in one package.

**Comment by galak** [comment]
> > 
> 
> what is the value of this? This is just unnecessary work IMO. I would rather spend the time on verifying this all in one package.

Fair point.

**Review by galak — APPROVED** [review]
We should change the major number on the release of this.

**Pull request merged**
